#%RAML 1.0 DataType

type: object
properties: 
    id: number
    user_id: number
    measurementDate: string
    timestamp: string
    height: number | nil
    waistline: number | nil
    weight: number | nil
    bodyMass: number | nil
    fatTotal: number | nil
    fatVisceral: number | nil