#%RAML 1.0 DataType
type: object
properties: 
  id: number
  username: string
  email: string
  firstName: string | nil
  lastName: string | nil
  dateOfBirth: string | nil
  role: number
  gender: string | nil
  public: boolean | nil
  token: string