#%RAML 1.0
title: Body dimensions API

types: 
  CreateUserType: !include types/CreateUserType.raml
  UserType: !include types/UserType.raml
  UserWithTokenType: !include types/UserWithTokenType.raml
  DeleteUsersType: !include types/DeleteUsersType.raml
  UpdateUserType: !include types/UpdateUserType.raml
  DeleteUserType: !include types/DeleteUserType.raml
  CreateMeasurementType: !include types/CreateMeasurementType.raml
  MeasurementType: !include types/MeasurementType.raml
  DeleteMeasumentsType: !include types/DeleteMeasurementsType.raml
  UpdateMeasurementType: !include types/UpdateMeasurementDataType.raml
  DeleteMeasurementType: !include types/DeleteMeasurementType.raml

/users:
  post:
    description: Create a new user
    body: 
      application/json:
        type: CreateUserType
        example: !include examples/CreateUpdateUserExample.raml
    responses: 
      201:
        body: 
          application/json:
            type: UserWithTokenType
            example: !include examples/UserWithTokenExample.raml
  get:
    description: Read all users
    responses: 
      200:
        body: 
          application/json:
            type: UserType[]
            example: !include examples/UsersExample.raml
  delete:
    description: Delete all users
    responses: 
      200:
        body: 
          application/json:
            type: DeleteUsersType
            example: !include examples/DeleteUsersExample.raml
  /{userId}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: UserType
              example: !include examples/UserExample.raml
    put:
      description: Update an existing users
      body: 
        application/json:
          type: UpdateUserType
          example: !include examples/CreateUpdateUserExample.raml
      responses: 
        200:
          body: 
            application/json:
              type: UserType
              example: !include examples/UserExample.raml
    delete:
      description: Delete existing user
      responses: 
        200:
          body:
            application/json:
              type: DeleteUserType
              example: !include examples/DeleteUserExample.raml
    /data:
      post:
        description: Create a new measurement item for user
        body: 
          application/json:
            type: CreateMeasurementType
        responses:
          201:
            body: 
              application/json:
                type: MeasurementType
                example: !include examples/MeasurementExample.raml
      get:
        description: Read user's measurement items
        responses: 
           200:
            body:
              application/json:
                type: MeasurementType[]
                example: !include examples/MeasurementsExample.raml
      delete:
        description: Delete all user's measurements
        responses: 
          200:
            body: 
              application/json:
                type: DeleteMeasumentsType
                example: !include examples/DeleteMeasurementsExample.raml
      /{data_id}:
        get:
          description: Read a measurement item
          responses: 
            200:
              body: 
                application/json:
                  type: MeasurementType
        put:
          description: Update a measurement item
          body:
            application/json:
              type: UpdateMeasurementType
              example: !include examples/UpdateMeasurementExample.raml
          responses: 
            200:
              body: 
                application/json:
                  type: MeasurementType
                  example: !include examples/MeasurementExample.raml
        delete:
          description: Delete a measurement item
          responses:
            200:
              body:
                application/json:
                  type: DeleteMeasurementType
                  example: !include examples/DeleteMeasurementExample.raml