#%RAML 1.0 NamedExample

value:
    username: jodo
    email: john@doe.com
    password: JohnDoe2000
    firstName: John
    lastName: Doe
    dateOfBirth: 2000-01-01
    gender: male
    public: true