#%RAML 1.0 NamedExample
value:
    id: 1
    user_id: 3
    measurementDate: 2000-01-02
    timestamp: 2018-10-15T06:35:50.134715
    height: 170
    waistline: 99
    weight: 100
    bodyMass: 30
    fatTotal: 30
    fatVisceral: 12