#%RAML 1.0 NamedExample
value:
  -
    id: 1
    user_id: 3
    measurementDate: 2000-01-02
    timestamp: 2018-10-13T06:35:50.134715
    height: 170
    waistline: null
    weight: null
    bodyMass: null
    fatTotal: null
    fatVisceral: null
  -
    id: 2
    user_id: 3
    measurementDate: 2000-01-03
    timestamp: 2018-10-14T06:35:50.134715
    height: null
    waistline: 99
    weight: null
    bodyMass: null
    fatTotal: null
    fatVisceral: null
  -
    id: 3
    user_id: 3
    measurementDate: 2000-01-04
    timestamp: 2018-10-15T06:35:50.134715
    height: null
    waistline: null
    weight: 100
    bodyMass: 30
    fatTotal: 30
    fatVisceral: 12