#%RAML 1.0 NamedExample
value:
    id: 2
    username: jodo
    email: john@doe.com
    firstName: John
    lastName: Doe
    dateOfBirth: 2000-01-01
    gender: male
    public: true
    role: 1
    numberOfMeasurements: 5