#%RAML 1.0 NamedExample
value:
    id: 2
    username: jodo
    email: john@doe.com
    firstName: John
    lastName: Doe
    dateOfBirth: Sat, 01 Jan 2000 00:00:00 GMT
    gender: male
    public: true
    role: 1
    token: eyJhbGciOiJIUzI1NiIsImlhdCI6MTUzOTQ1MTIyNiwiZXhwIjoxNTM5NDUxODI2fQ.eyJpZCI6MiwidXNlcm5hbWUiOiJ0ZXN0MDEiLCJyb2xlIjoidXNlciJ9.2fP4kiEStepDUypj2U2e90ITx77hHi7AKWM-m6OX5mM",