#%RAML 1.0 NamedExample
value:
  -
    id: 1
    username: admin
    email: default
    firstName: null
    lastName: null
    dateOfBirth: null
    gender: null
    public: null
    role: 0
    numberOfMeasurements: 0
  -
    id: 2
    username: jodo
    email: john@doe.com
    firstName: John
    lastName: Doe
    dateOfBirth: 2000-01-01
    gender: male
    public: true
    role: 1
    numberOfMeasurements: 5
  -
    id: 3
    username: jedo
    email: jane@doe.com
    firstName: John
    lastName: Doe
    dateOfBirth: 2001-01-01
    gender: female
    public: true
    role: 1
    numberOfMeasurements: 5
  -
    id: 4
    username: anonymous
    email: anonymous@user.com
    firstName: null
    lastName: null
    dateOfBirth: null
    gender: null
    public: false
    role: 1
    numberOfMeasurements: 800